filebeat.inputs:
  - type: log
    paths:
      - ingest_data/proxysql-data/*.log*
    json:
      keys_under_root: true
      add_error_key: true

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

setup.template:
  name: "proxysql-logs"
  pattern: "proxysql-logs-*"
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "/usr/share/filebeat/certs/ca/ca.crt"
  index: "proxysql-logs-%{+yyyy.MM.dd}"

monitoring.enabled: false
logging.level: debug
